name: Package

on:
  push:
    tags:
      - "*"

jobs:
  node-script-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: cp cli-dist.js ckb-transaction-dumper
      - run: tar czf ckb-transaction-dumper_v${{  github.ref_name }}_node_executable_script.tar.gz ckb-transaction-dumper README.md LICENSE
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ckb-transaction-dumper_v${{  github.ref_name }}_node_executable_script.tar.gz

  linux-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npx pkg --options "no-warnings" -t node18-linux-x64 cli-dist.js -o ckb-transaction-dumper
      - run: tar czf ckb-transaction-dumper_v${{  github.ref_name }}_linux_x86_64.tar.gz ckb-transaction-dumper README.md LICENSE
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ckb-transaction-dumper_v${{  github.ref_name }}_linux_x86_64.tar.gz

  macos-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npx pkg --options "no-warnings" -t node18-macos-x64 cli-dist.js -o ckb-transaction-dumper
      - run: tar czf ckb-transaction-dumper_v${{  github.ref_name }}_macos_x86_64.tar.gz ckb-transaction-dumper README.md LICENSE
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ckb-transaction-dumper_v${{  github.ref_name }}_macos_x86_64.tar.gz

  windows-release:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - run: npx pkg --options "no-warnings" -t node18-win-x64 cli-dist.js -o ckb-transaction-dumper
      - run: Compress-Archive -Path ckb-transaction-dumper, README.md, LICENSE -DestinationPath ckb-transaction-dumper_v${{  github.ref_name }}_win_x86_64.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ckb-transaction-dumper_v${{  github.ref_name }}_win_x86_64.zip
